BMI/Models/Man.cs
using System;
using BMI.Models;

namespace BMI.Controllers {
    public class Man : IShowBMIResult {
        private double _BMI;
        public Man(double BMI) {
            _BMI = BMI;
        }
        private string _result;
        public string result { get { return _result; } }

        public string ShowResult() {
            if (_BMI < 20) _result = "太瘦";
            if (_BMI >= 25) _result = "太胖";
            if (20 <= _BMI && _BMI < 25) _result = "適中";
            return _result;
        }
    }
}

BMI/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using BMI.Controllers;

namespace BMI.Models {
    public class Person {
        [Display(Name = "身高")]
        public int CM { get; set; }
        [Display(Name = "體重")]
        public int KG { get; set; }
    }

    public class BMIResult {
        public Person person { get; set; }
        public IShowBMIResult man { get; set; }
        public IShowBMIResult woman { get; set; }
        public double BMI { get; set; }
    }

    public interface IShowBMIResult {
        string ShowResult();
    }
}

BMI/Models/Woman.cs
using System;
using BMI.Models;

namespace BMI.Controllers {
    public class Woman : IShowBMIResult {
        private double _BMI;
        public Woman(double BMI) {
            _BMI = BMI;
        }
        private string _result;
        public string result { get { return _result; } }
        public string ShowResult() {
            if (_BMI < 18) _result = "太瘦";
            if (_BMI >= 22) _result = "太胖";
            if (18 <= _BMI && _BMI < 22) _result = "適中";
            return _result;
        }
    }
}

BMI/Controllers/BMIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BMI.Models;

namespace BMI.Controllers
{
    public class BMIController : Controller
    {
        // GET: BMI
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Person person) {
            //驗證輸入資料
            if (person == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //計算BMI
            double BMIValue = new BMICal().CalcutedBMI(person);

            //計算男生結果
            IShowBMIResult man = new Man(BMIValue);
            man.ShowResult();

            //計算女生結果
            IShowBMIResult woman = new Woman(BMIValue);
            woman.ShowResult();

            //輸出結果
            BMIResult result = CreateResult(person, BMIValue, man, woman);
            return View(result);

        }

        /// <summary>
        /// 計算BMI
        /// </summary>
        /// <param name="person"></param>
        /// <param name="BMIValue"></param>
        /// <param name="man"></param>
        /// <param name="woman"></param>
        /// <returns></returns>
        private static BMIResult CreateResult(Person person, double BMIValue, IShowBMIResult man, IShowBMIResult woman) {
            return new BMIResult {
                BMI = BMIValue,
                man = man,
                woman = woman,
                person = person
            };
        }
    }
}

BMI/Views/BMI/Create.cshtml
@using BMI.Models

<h2>您的身高：@(Model.person.CM)公分、體重：@(Model.person.KG)公斤。BMI計算結果為：@Model.BMI</h2>
<h4>若您是男生，則@(Model.man.result)；若您是女生，則@(Model.woman.result)。</h4>

BMI/Views/BMI/Index.cshtml
@model BMI.Models.Person

@{
    ViewBag.Title = "Index";
}

<h2>計算你的BMI</h2>

@using (Html.BeginForm("Create", "BMI", FormMethod.Post)) {
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>請輸入身高、體重進行計算</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="開始計算" class="btn btn-default" />
            </div>
        </div>
    </div>
}

BMI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>